# Generated by Django 2.0.4 on 2018-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='color',
            field=models.CharField(max_length=6, verbose_name='Color'),
        ),
    ]
